# Generated by Django 5.1.5 on 2026-01-28 01:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0008_add_email_notifications_preference'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSPViolation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_uri', models.URLField(help_text='URI do documento que violou CSP (normalizada)', max_length=500)),
                ('violated_directive', models.CharField(help_text='Diretiva CSP que foi violada', max_length=100)),
                ('effective_directive', models.CharField(help_text='Diretiva efetiva que foi violada', max_length=100)),
                ('original_policy', models.TextField(help_text='Política CSP original')),
                ('blocked_uri', models.CharField(blank=True, help_text='URI bloqueada (sanitizada, sem query params)', max_length=500, null=True)),
                ('source_file', models.CharField(blank=True, help_text='Arquivo fonte (sanitizado)', max_length=500, null=True)),
                ('line_number', models.PositiveIntegerField(blank=True, help_text='Número da linha onde ocorreu a violação', null=True)),
                ('user_agent', models.CharField(blank=True, help_text='User agent truncado (primeiros 200 chars)', max_length=200, null=True)),
                ('ip_address', models.GenericIPAddressField(help_text='IP do cliente (para rate limiting)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(help_text='Tenant que reportou a violação', on_delete=django.db.models.deletion.CASCADE, related_name='csp_violations', to='tenants.client')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['client', 'created_at'], name='core_cspvio_client__5d48f3_idx'), models.Index(fields=['violated_directive'], name='core_cspvio_violate_7ffd88_idx'), models.Index(fields=['ip_address'], name='core_cspvio_ip_addr_01efd8_idx')],
            },
        ),
    ]
