# Generated by Django 6.0.1 on 2026-01-11 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='data_resposta',
            field=models.DateTimeField(blank=True, help_text='Data em que a empresa respondeu', null=True, verbose_name='Data da Resposta'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='protocolo',
            field=models.CharField(blank=True, db_index=True, editable=False, help_text='Código único de rastreamento do feedback', max_length=20, null=True, unique=True, verbose_name='Protocolo'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='resposta_empresa',
            field=models.TextField(blank=True, help_text='Resposta ou posicionamento da empresa sobre o feedback', null=True, verbose_name='Resposta da Empresa'),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['protocolo'], name='feedbacks_f_protoco_99cb05_idx'),
        ),
    ]
