# Generated by Django 6.0.1 on 2026-01-12 01:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0002_feedback_data_resposta_feedback_protocolo_and_more'),
        ('tenants', '0003_client_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackInteracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.TextField(verbose_name='Mensagem / Descrição')),
                ('tipo', models.CharField(choices=[('MENSAGEM_PUBLICA', 'Mensagem Pública'), ('NOTA_INTERNA', 'Nota Interna'), ('MUDANCA_STATUS', 'Mudança de Status')], max_length=20, verbose_name='Tipo de Interação')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('client', models.ForeignKey(help_text='Cliente (tenant) ao qual este registro pertence', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.client', verbose_name='Cliente')),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interacoes', to='feedbacks.feedback', verbose_name='Feedback')),
            ],
            options={
                'verbose_name': 'Interação do Feedback',
                'verbose_name_plural': 'Interações do Feedback',
                'ordering': ['-data'],
                'indexes': [models.Index(fields=['client'], name='feedbacks_f_client__5cf6ad_idx'), models.Index(fields=['feedback', 'data'], name='feedbacks_f_feedbac_f74813_idx'), models.Index(fields=['tipo'], name='feedbacks_f_tipo_5cd270_idx')],
            },
        ),
    ]
