# Generated by Django 6.0.1 on 2026-01-11 18:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        help_text="Nome da empresa cliente",
                        max_length=100,
                        verbose_name="Nome da Empresa",
                    ),
                ),
                (
                    "subdominio",
                    models.SlugField(
                        help_text="Subdomínio único para acesso (ex: empresaA)",
                        max_length=63,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Subdomínio deve conter apenas letras minúsculas, números e hífens",
                                regex="^[a-z0-9]([a-z0-9-]*[a-z0-9])?$",
                            )
                        ],
                        verbose_name="Subdomínio",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        help_text="Logo da empresa para white label",
                        null=True,
                        upload_to="tenants/logos/",
                        verbose_name="Logo",
                    ),
                ),
                (
                    "cor_primaria",
                    models.CharField(
                        default="#3B82F6",
                        help_text="Cor primária da interface em hexadecimal",
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Cor deve estar no formato hexadecimal (ex: #3B82F6)",
                                regex="^#[0-9A-Fa-f]{6}$",
                            )
                        ],
                        verbose_name="Cor Primária",
                    ),
                ),
                (
                    "ativo",
                    models.BooleanField(
                        default=True,
                        help_text="Define se o tenant está ativo no sistema",
                        verbose_name="Ativo",
                    ),
                ),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "data_atualizacao",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
            ],
            options={
                "verbose_name": "Cliente",
                "verbose_name_plural": "Clientes",
                "ordering": ["nome"],
            },
        ),
    ]
