# Generated by Django 6.0.1 on 2026-01-27 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0007_populate_team_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='email_notifications',
            field=models.BooleanField(default=True, help_text='Se desabilitado, não receberá emails de atribuição/novos feedbacks', verbose_name='Receber notificações por email'),
        ),
    ]
