# Generated by Django 5.1.5 on 2026-01-29 14:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0008_add_email_notifications_preference'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=50, verbose_name='Tipo de Evento')),
                ('payload', models.JSONField(verbose_name='Payload')),
                ('source_model', models.CharField(blank=True, max_length=50, verbose_name='Model de Origem')),
                ('source_id', models.CharField(blank=True, max_length=50, verbose_name='ID de Origem')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('processing', 'Processando'), ('delivered', 'Entregue'), ('failed', 'Falhou'), ('partial', 'Parcial')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Webhook Event',
                'verbose_name_plural': 'Webhook Events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookEndpoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('url', models.URLField(verbose_name='URL do Webhook')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('secret', models.CharField(editable=False, max_length=64, verbose_name='Secret Key')),
                ('events', models.JSONField(default=list, verbose_name='Eventos')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('headers', models.JSONField(blank=True, default=dict, verbose_name='Headers Customizados')),
                ('max_retries', models.PositiveSmallIntegerField(default=3, verbose_name='Máximo de Retentativas')),
                ('retry_delay', models.PositiveIntegerField(default=60, verbose_name='Delay entre Retentativas (seg)')),
                ('total_deliveries', models.PositiveIntegerField(default=0)),
                ('successful_deliveries', models.PositiveIntegerField(default=0)),
                ('failed_deliveries', models.PositiveIntegerField(default=0)),
                ('last_triggered', models.DateTimeField(blank=True, null=True)),
                ('last_success', models.DateTimeField(blank=True, null=True)),
                ('last_failure', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(help_text='Cliente (tenant) ao qual este registro pertence', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.client', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Webhook Endpoint',
                'verbose_name_plural': 'Webhook Endpoints',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_url', models.URLField(verbose_name='URL')),
                ('request_headers', models.JSONField(default=dict, verbose_name='Headers')),
                ('request_payload', models.JSONField(verbose_name='Payload Enviado')),
                ('response_status', models.IntegerField(null=True, verbose_name='Status Code')),
                ('response_headers', models.JSONField(default=dict, verbose_name='Response Headers')),
                ('response_body', models.TextField(blank=True, verbose_name='Response Body')),
                ('duration_ms', models.PositiveIntegerField(null=True, verbose_name='Duração (ms)')),
                ('success', models.BooleanField(default=False, verbose_name='Sucesso')),
                ('error_message', models.TextField(blank=True, verbose_name='Mensagem de Erro')),
                ('attempt', models.PositiveSmallIntegerField(default=1, verbose_name='Tentativa')),
                ('next_retry_at', models.DateTimeField(blank=True, null=True, verbose_name='Próxima Tentativa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='webhooks.webhookendpoint')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='webhooks.webhookevent')),
            ],
            options={
                'verbose_name': 'Webhook Delivery',
                'verbose_name_plural': 'Webhook Deliveries',
                'ordering': ['-created_at'],
            },
        ),
    ]
