# Generated by Django 6.0.1 on 2026-01-11 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('denuncia', 'Denúncia'), ('sugestao', 'Sugestão'), ('elogio', 'Elogio'), ('reclamacao', 'Reclamação')], help_text='Tipo de feedback', max_length=20, verbose_name='Tipo')),
                ('titulo', models.CharField(help_text='Título do feedback', max_length=200, verbose_name='Título')),
                ('descricao', models.TextField(help_text='Descrição detalhada do feedback', verbose_name='Descrição')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_analise', 'Em Análise'), ('resolvido', 'Resolvido'), ('fechado', 'Fechado')], default='pendente', help_text='Status atual do feedback', max_length=20, verbose_name='Status')),
                ('anonimo', models.BooleanField(default=False, help_text='Feedback enviado anonimamente', verbose_name='Anônimo')),
                ('email_contato', models.EmailField(blank=True, help_text='E-mail para retorno (opcional se anônimo)', max_length=254, null=True, verbose_name='E-mail de Contato')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('client', models.ForeignKey(help_text='Cliente (tenant) ao qual este registro pertence', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.client', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedbacks',
                'ordering': ['-data_criacao'],
                'indexes': [models.Index(fields=['client', 'tipo'], name='feedbacks_f_client__159ef9_idx'), models.Index(fields=['client', 'status'], name='feedbacks_f_client__fc3f7e_idx')],
            },
        ),
    ]
