# Generated by Django 6.0.1 on 2026-01-27 01:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedbacks", "0008_add_feedback_assignment"),
        ("tenants", "0008_add_email_notifications_preference"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        help_text="Nome da tag (ex: Urgente, Bug, Feature Request)",
                        max_length=50,
                        verbose_name="Nome",
                    ),
                ),
                (
                    "cor",
                    models.CharField(
                        default="#3B82F6",
                        help_text="Cor em hexadecimal (#RRGGBB)",
                        max_length=7,
                        verbose_name="Cor",
                    ),
                ),
                (
                    "descricao",
                    models.TextField(
                        blank=True,
                        help_text="Descrição opcional do propósito da tag",
                        verbose_name="Descrição",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "client",
                    models.ForeignKey(
                        help_text="Cliente (tenant) ao qual este registro pertence",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="tenants.client",
                        verbose_name="Cliente",
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tags_criadas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tag",
                "verbose_name_plural": "Tags",
                "ordering": ["nome"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="feedback",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                help_text="Tags para categorização do feedback",
                related_name="feedbacks",
                to="feedbacks.tag",
                verbose_name="Tags",
            ),
        ),
        migrations.AddIndex(
            model_name="tag",
            index=models.Index(
                fields=["client", "nome"], name="feedbacks_t_client__0bea69_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="tag",
            unique_together={("client", "nome")},
        ),
    ]
