# Generated by Django 5.1.15 on 2026-02-06 13:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedbacks", "0012_add_response_template"),
        ("tenants", "0008_add_email_notifications_preference"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="feedback",
            index=models.Index(
                fields=["client", "prioridade", "-data_criacao"],
                name="feedback_priority_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="feedback",
            index=models.Index(
                fields=["client", "assigned_to", "status"],
                name="feedback_assigned_status_idx",
            ),
        ),
    ]
